version: "3.8"

services:
  nginx:
    image: nginx:1.24.0
    ports:
      - 8081:80
    networks:
      - myNetwork
    restart: always
    configs:
      - source: nginx_config
        target: /etc/nginx/conf.d/default.conf
    deploy:
      mode: global

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - myNetwork
    restart: always
    deploy:
      placement:
        constraints:
          - "node.labels.TAG==postgres"

networks:
  myNetwork:
    driver: overlay

configs:
  nginx_config:
    file: ./default.conf

volumes:
  data:
    name: data