version: '3'

services:
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - my-pg-network
    restart: always

volumes:
  data:
    name: data

networks:
  my-pg-network:
    name: my-pg-network