galaxy_info:
  role_name: install_users
  description: Создание пользователей
  author: Ilya Romanyuk
  license: MIT
  min_ansible_version: '2.15'
  platforms:
    - name: Ubuntu
      versions:
        - all